# This workflow will build a .NET project with both .NET 8 and .NET 9 SDKs,
# and publish the resulting nupkg file(s) as an artifact.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Multi-SDK Build & Publish

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c ${{ env.BUILD_CONFIGURATION }}

    - name: Test
      run: dotnet test

    - name: Copy NuGet package(s) to artifact staging directory
      run: |
        mkdir -p ./nupkgs
        cp src/Benday.CommandsFramework/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg ./nupkgs/
    
    - name: Publish nupkg artifact
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: ./nupkgs/*.nupkg